(function(){
  function easter(y){var a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=((h+l-7*m+114)%31)+1;return new Date(Date.UTC(y,mo-1,da));}
  function addDays(d,n){var x=new Date(d.getTime());x.setUTCDate(x.getUTCDate()+n);return x;}
  function iso(d){return d.toISOString().slice(0,10);}
  var MONTHS_DK=['januar','februar','marts','april','maj','juni','juli','august','september','oktober','november','december'];
  function fmtDK(d){return d.getUTCDate()+'. '+MONTHS_DK[d.getUTCMonth()]+' '+d.getUTCFullYear();}
  function holidays(y){var e=easter(y),out=[];function push(d,n){out.push([iso(d),n]);}push(new Date(Date.UTC(y,0,1)),'Nytårsdag');push(addDays(e,-3),'Skærtorsdag');push(addDays(e,-2),'Langfredag');push(e,'Påskedag');push(addDays(e,1),'2. påskedag');push(addDays(e,39),'Kristi himmelfartsdag');push(addDays(e,49),'Pinsedag');push(addDays(e,50),'2. pinsedag');push(new Date(Date.UTC(y,11,25)),'Juledag');push(new Date(Date.UTC(y,11,26)),'2. juledag');return new Map(out);}
  function optional(y){return new Set([iso(new Date(Date.UTC(y,4,1))),iso(new Date(Date.UTC(y,5,5))),iso(new Date(Date.UTC(y,11,24))),iso(new Date(Date.UTC(y,11,31)))]);}
  function parse(s){var p=s.split('-').map(Number);return new Date(Date.UTC(p[0],p[1]-1,p[2]));}
  function isWorkday(d,includeOffice){var wd=d.getUTCDay();if(wd===0||wd===6)return false;var id=iso(d);if(holidays(d.getUTCFullYear()).has(id))return false;if(includeOffice&&optional(d.getUTCFullYear()).has(id))return false;return true;}
  function fmt(n){return new Intl.NumberFormat('da-DK').format(n);}
  function between(){var start=document.getElementById('bd-start'),end=document.getElementById('bd-end'),mode=document.getElementById('bd-mode'),out=document.getElementById('bd-result');if(!start||!end||!out)return;var a=parse(start.value),b=parse(end.value);if(isNaN(a)||isNaN(b)||b<a){out.innerHTML='Vælg en gyldig start- og slutdato.';return;}var incl=mode.value==='office',days=0,total=0,hol=[];for(var d=a;d<=b;d=addDays(d,1)){total++;if(isWorkday(d,incl))days++;var h=holidays(d.getUTCFullYear()).get(iso(d));if(h)hol.push(h+' ('+fmtDK(d)+')');}out.innerHTML='<strong>'+fmt(days)+' arbejdsdage</strong><br><span>'+fmt(total)+' kalenderdage i perioden.</span>'+(hol.length?'<br><small>Helligdage i perioden: '+hol.join(', ')+'</small>':'');}
  function addBusiness(){var start=document.getElementById('add-start'),amount=document.getElementById('add-amount'),mode=document.getElementById('add-mode'),out=document.getElementById('add-result');if(!start||!amount||!out)return;var d=parse(start.value),n=parseInt(amount.value,10)||0,incl=mode.value==='office';if(isNaN(d)||n<0){out.innerHTML='Vælg en gyldig dato og antal dage.';return;}var left=n;while(left>0){d=addDays(d,1);if(isWorkday(d,incl))left--;}out.innerHTML='<strong>'+fmtDK(d)+'</strong><br><span>'+d.toLocaleDateString('da-DK',{weekday:'long',timeZone:'UTC'})+'</span>';}
  function weekNumber(){var input=document.getElementById('week-date'),out=document.getElementById('week-result');if(!input||!out)return;var d=parse(input.value);if(isNaN(d)){out.innerHTML='Vælg en dato.';return;}var tmp=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));var day=tmp.getUTCDay()||7;tmp.setUTCDate(tmp.getUTCDate()+4-day);var yStart=new Date(Date.UTC(tmp.getUTCFullYear(),0,1));var week=Math.ceil((((tmp-yStart)/86400000)+1)/7);out.innerHTML='<strong>Uge '+week+'</strong><br><span>'+fmtDK(d)+' ligger i ISO-uge '+week+'.</span>';}
  document.addEventListener('input',between);document.addEventListener('change',between);document.addEventListener('input',addBusiness);document.addEventListener('change',addBusiness);document.addEventListener('input',weekNumber);document.addEventListener('change',weekNumber);between();addBusiness();weekNumber();
})();
